# Generated by Django 4.2.3 on 2023-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expiration',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
